name: CI
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-22.04
    name: lint
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: sudo apt-get update && sudo apt-get install -y curl
      - run: curl -sSL https://install.python-poetry.org | POETRY_VERSION=1.4.1 python3 -
      - run: poetry install --all-extras
      - run: poetry check
      - run: poetry run ruff check ./sqlargon
      - run: poetry run black ./sqlargon --check
      - run: poetry run isort ./sqlargon --check
      - run: poetry run mypy ./sqlargon
      - run: poetry run deptry ./sqlargon
      - run: poetry run bandit -r ./sqlargon

  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os: ["ubuntu-22.04"]
        python: ["3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}
    name: test on ${{ matrix.python }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: sudo apt-get update && sudo apt-get install -y gcc curl
      - run: curl -sSL https://install.python-poetry.org | python3 -
      - run: poetry install --all-extras
      - run: poetry run pytest --cov=./sqlargon --cov-report=xml -v ./tests
